# Streamlit Secrets Configuration
# This file should be configured in your Streamlit Cloud app settings
# Go to your app on share.streamlit.io -> Settings -> Secrets

[mongo]
uri = "mongodb+srv://asifabu128_db_user:4ZSK8mg4aHfHbJlm@cluster0.pn5fybo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Example MongoDB Atlas connection string:
# uri = "mongodb+srv://myuser:mypassword@cluster0.abc123.mongodb.net/meeting_summarizer?retryWrites=true&w=majority"

# Instructions:
# 1. Replace <username> with your MongoDB Atlas username
# 2. Replace <password> with your MongoDB Atlas password  
# 3. Replace cluster0.xxxxx with your actual cluster URL
# 4. Update the database name if needed (currently: meeting_summarizer)
# 5. Make sure your MongoDB Atlas cluster allows connections from 0.0.0.0/0

# How to get your connection string:
# 1. Go to MongoDB Atlas dashboard
# 2. Click "Connect" on your cluster
# 3. Choose "Connect your application"
# 4. Select "Python" and copy the connection string
# 5. Replace <password> with your actual database user password
